##Docsï¼šhttps://yun.yunyoujun.cn/guide/
##ICON:https://icones.js.org/
##è¯­è¨€
language: zh-CN

#é€šçŸ¥æ 
notice:
  enable: true
  content: â€»ç½®é¡¶:ä»Šå¹´æˆ‘è¦å»å¹¿è¥¿å£®æ—è‡ªæ²»åŒºæ¢§å·å¸‚/é˜²åŸæ¸¯å¸‚ä¸œå…´å¸‚ã€å¹¿ä¸œçœæ·±åœ³å¸‚/ä¸œèå¸‚/ç æµ·å¸‚/å¹¿å·å¸‚ã€è¾½å®çœæ²ˆé˜³å¸‚ã€å±±ä¸œçœé’å²›å¸‚ã€é¦™æ¸¯/æ¾³é—¨ç‰¹åˆ«è¡Œæ”¿åŒºã€ä¿„ç½—æ–¯å›½å“ˆå·´ç½—å¤«æ–¯å…‹ï¼ˆä¼¯åŠ›ï¼‰ç­‰Â·Â·Â·Â·Â·Â· | (UTC+8)2025-02-21 01:45:12
say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

#æ ‡ç­¾ã€åˆ†ç±»é¢œè‰²
#tags: 
#categories: 

##å¤´éƒ¨èµ„æº
head:
  css:
  
  js:
    base:
    async:
    defer:  

pjax:
  enable: true
#æ”¾å¤§é¢„è§ˆå›¾ç‰‡
medium_zoom: true
#é¦–é¡µå¡ç‰‡ä¸æ–‡ç« å†…éƒ¨å›¾ç‰‡çš„æ»šåŠ¨æµ®ç°æ•ˆæœ
scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img
#å…‰æ ‡
cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur  
###ä¸»é¡µè®¾ç½®
favicon: /favicon.ico #ç½‘é¡µå›¾æ ‡
##ä¸»é¢˜è‰²
mode: auto #é»‘ç™½å¤œæ¨¡å¼
mourn:
  enable: true
  days:
    - 4-4
    - 9-18
    - 12-23
colors:
  primary: '#e5aa82'
  # bg: "#F5F5F5"
  selection_bg: '#dcc48c' # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
wordcloud:
  enable: true
 # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  #tag_start_color: '#d0b9db'
  #tag_end_color: '#5c3c9e'
##ä¸»é¢˜è‰ºæœ¯æ ‡é¢˜å­—
banner:
  enable: true
  title: 
  - æ²
  - ä½š
  - è‹‘
  - é˜
  - MuYi
  - Pavilion
  border: true
  cloud:
    enable: true
    color: yellow
  go_down:
    enable: true
    icon: cib:apache-airflow
bg_image: #å›¾ç‰‡èƒŒæ™¯
  enable: true
  url: https://2dcaf961.telegraph-image-2qa.pages.dev/file/6f397636d7cee1ad17a70.jpg
  dark: https://2dcaf961.telegraph-image-2qa.pages.dev/file/f4874c2bbc98f106d2e9b.jpg
  blur: 5px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 1.0
trianglify: #ä¸è§„åˆ™å›¾å½¢èƒŒæ™¯
  enable: false
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5  
fireworks: #çƒŸèŠ±
  enable: true
  colors:
    - '203, 117, 203'
    - '219, 168, 182'
    - '193, 184, 179'


##ä¾§è¾¹æ 
sidebar:
  bg_image: https://telegraph-img-by-bot.pages.dev/file/56a21040acdf06a3b8ccc.jpg
  bg_position: bottom 0rem center
  tagcloud:
    enable: false
    amount: 20
avatar:
  enable: true
  url: https://q.qlogo.cn/headimg_dl?dst_uin=1215372633&spec=640&img_type=jpg  
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ¬
    message: Sweet Dream
menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-2-line
    - type: categories
      path: /categories/
      icon: ri:folders-line
    - type: tags
      path: /tags/
      icon: ri:bookmark-line
  custom:
    title: Repositories Pages
    path: https://github.com/JayMuShui/jaymushui.github.io
    icon: uil:github-alt
pages:
  #- name: My Gooooooooood Friends
  #  url: /links/
  #  icon: uil:channel
  #  color: dodgerblue
social:
  - name: E-Mail
    link: mailto:JayMuShui@outlook.com
    icon: ri:mail-line
    color: '#8E71C1'

  - name: GitHub
    link: https://github.com/JayMuShui
    icon: ri:github-line
    color: '#6e5494'

  - name: X
    link: https://x.com/JayMuShui
    icon: ri:twitter-x-fill
    color: '#000000'

  - name: Telegram
    link: https://t.me/JayMuShui
    icon: ri:telegram-line
    color: '#0088CC'
  
  - name: Discord
    link: https://discord.gg/phTwnqcTb6
    icon: ri:discord-line
    color: '#5A6DE2'
  
  - name: QQ
    link: https://telegraph-img-by-bot.pages.dev/file/7d33f995cab76537ff1db.jpg
    icon: ri:qq-line
    color: '#12B7F5'
  
  - name: å¾®ä¿¡å…¬ä¼—å· | WeChat Public Platform
    link: https://telegraph-img-by-bot.pages.dev/file/1729946797712_å…¬ä¼—å·.png
    icon: ri:wechat-fill
    color: '#54dc64'
  
  - name: å“”å“©å“”å“© | Bilibili
    link: https://space.bilibili.com/447538884
    icon: ri:bilibili-line
    color: '#FF8EB3'
  
  - name: æŠ–éŸ³ | Chinese Tiktok/Douyin
    link: https://v.douyin.com/ijnW2SjQ/
    icon: ri:tiktok-line
    color: '#000000'
  
  - name: ç™¾åº¦è´´å§ | Tieba
    link: https://tieba.baidu.com/home/main?id=tb.1.59e2d8be.7M1jjgg8P1zLx8vptZ7Vdw
    icon: ri:baidu-line
    color: '#0084FF'
  
  - name: çŸ¥ä¹ | Zhihu
    link: https://www.zhihu.com/people/jaymushui
    icon: ri:zhihu-line
    color: '#0084FF'
  
  - name: æ–°æµªå¾®åš|Sina Weibo
    link: https://weibo.com/u/6509902620
    icon: ri:weibo-line
    color: '#ca5963'
  
  

  

###æ–‡ç« 
mermaid:
  enable: true
  options: # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    startOnload: true # default true
  global: true # default true
post_card:
  opacity: 0.7
creative_commons:
  license: by-nc-sa
  post: false
  language: deed.zh
  clipboard: false
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true
reward:
  enable: true
  icon: ri:hand-coin-line
  comment: æˆ‘æ˜¯å­¦ç”Ÿï¼Œè¯·ç»™æˆ‘æ‰“é’±ã€‚
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: æ”¯ä»˜å®
      path: https://telegraph-img-by-bot.pages.dev/file/1729947121338_Alipay.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
      #link:
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://telegraph-img-by-bot.pages.dev/file/1729947118099_WeChatPay.png
      color: '#2DC100'
      icon: ri:wechat-pay-line
      #link:
    - name: QQ æ”¯ä»˜
      path: https://telegraph-img-by-bot.pages.dev/file/1729947117502_QQPay.png
      color: '#12B7F5'
      icon: ri:qq-line
      #link:

##é¡µè„š
footer:
  since: 2024
  icon:
    name: ri:github-line
    animated: true
    color: '#cb75cb'
    url: https://github.com/JayMuShui/jaymushui.github.io
    title: Github Repositories
  powered:
    enable: true
  footer:
  # å¤‡æ¡ˆ
  beian:
    enable: false
    icp: æ¡‚ICPå¤‡xxxxxxxxå·
    gongan:
      enable: false
      text: æ¡‚å…¬ç½‘å®‰å¤‡ XXXXXXXX å·
      id: XXXXXXXX
  live_time:
    enable: true
    prefix: Operational Time | è¿è¥æ—¶é—´ ï¼š
    suffix: QWQ
    start_time: '2024-06-16T00:00:00'
  support:
    enable: false
    title: /
    link: /
    logo: /
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾› CDN åŠ é€Ÿ
  custom_text: å·²ç»åˆ°è¾¾åº•éƒ¨å•¦!

##æœç´¢ä¸ç»Ÿè®¡
local_search:
  enable: true
engine_search:
  enable: false
  href: 'https://www.google.com/search?q=site:'
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: /
busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: ri:user-line
  site_pv: true
  site_pv_icon: ri:eye-line
  page_pv: true
  page_pv_icon: ri:eye-line
wordcount:
  enable: true
  count: true
  time: true

aplayer:
  global: true
  meting: true
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: true
    autoplay: false
    # theme: "#2980b9"
    loop: all
    order: list
    preload: auto
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: false
    listMaxHeight: 340px
    audio:
      - name: /
        artist: /
        url: /
        cover: /
    meting:
      enable: true
      id: 12565693599
      server: netease
      type: playlist

